stair_mode_controller:
  ros__parameters:
    map_frame: map
    base_frame: base_link
    control_topic: /keyboard_control
    check_rate: 20.0

    x_min: 4.200
    x_max: 5.200
    y_min: 2.000
    y_max: 4.500

    target_yaw_deg: -90.0
    yaw_tolerance_deg: 60.0

    flat_length_leg: 1
    stair_length_leg: 2
    spin_mode: 0
